name: Run tests

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --development

      - name: Build
        run: bun run build

      - name: Typecheck
        run: bun run typecheck

      - name: Tests
        run: bun run test
